spring.application.name=classicamoveis

# Configuração local para desenvolvimento sem depender de MySQL externo
spring.datasource.url=jdbc:h2:mem:classica;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=oJ+NGEttZ/OM9JJ6EethEX/RXmjMT4tvtfRzA7PvHH3PXTOn2WRUoCmjxiFx8CUUNWDMnS8mNw0SytuoM2fB3w==
jwt.validity=86400